//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VWH
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudPars
    {
        public int id_Check { get; set; }
        public int Stud_id { get; set; }
        public int par_id { get; set; }
        public int datePar_id { get; set; }
        public bool ChecStat { get; set; }
    
        public virtual DatePars DatePars { get; set; }
        public virtual Pars Pars { get; set; }
        public virtual stud stud { get; set; }
    }
}
