//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Studs
    {
        public int id_Stud { get; set; }
        public string Name { get; set; }
        public string Groop { get; set; }
        public string Colors { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
